# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-paginate

# Permalinks
permalink: pretty

# Setup
title: Yale Astro x Data Science
tagline: 'Yale Data Science x Astronomy-Astrophysics Seminar'
description: 'The Yale Data Science x Astronomy-Astrophysics Seminar Series'
url: https://yale-dsaas.github.io/
baseurl: ""

author:
  name: 'Yasmeen Asali'
  url: https://yasmeenasali.com

paginate: 1 # Only one post per page
paginate_path: "/page:num/"
